### ISSUE TITLE
Link to exact User 

### ISSUE THREAD

**Issue by ginggk** [CodyvanderPoel/CodyvanderPoel.github.io#1]
https://github.com/CodyvanderPoel/CodyvanderPoel.github.io/blob/bb8d1723d76f2a5841fd6c40c1c46c4ec9ebc800/index.html#L111

Hi Cody! 

I noticed that your linkedin link, when you click it goes to the home page of LinkedIn. I thought it might be beneficial, if you wanted, to link it to your exact user page. A way to do this would be 'https://linkedin.com/cody-van-der-poel-37a42516b' in your href.

**Comment by CodyvanderPoel** [comment]
I added that in, I had to do a special link for myself, so try it whenever you can, and let me know if it works.

**Comment by ginggk** [comment]
Hi! 

It now says Page Not Found?

**Comment by CodyvanderPoel** [comment]
I figured it would, I'll try the other solution I found.

**Comment by CodyvanderPoel** [comment]
The other solution is now pushed.
