### ISSUE TITLE
Missing Word

### ISSUE THREAD

**Issue by ginggk** [CodyvanderPoel/CodyvanderPoel.github.io#2]
https://github.com/CodyvanderPoel/CodyvanderPoel.github.io/blob/bb8d1723d76f2a5841fd6c40c1c46c4ec9ebc800/index.html#L111

Hi Cody! 

You said right here 'on the other', I think a better way to say it would be 'on the other hand'.

**Comment by CodyvanderPoel** [comment]
Thanks for catching that.
